# Generated by Django 5.2.4 on 2025-07-28 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código de resgate')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número máximo de resgates')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Resgatado em')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon', verbose_name='Cupom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resgate',
                'verbose_name_plural': 'Resgates',
                'ordering': ['-redeemed_at'],
                'unique_together': {('user', 'coupon', 'redeemed_at')},
            },
        ),
    ]
